import { useLayoutEffect, useRef, useState } from "react";
import styles from "../styles/Register.module.css";
import Head from "next/head";
import { useRegisterMutation } from "features/auth/authApiSlice";
import { useGetAllBranchCodesMutation } from "features/branchcode/branchcodeApiSlice";
import { useRouter } from "next/router";
import { setCredentials } from "features/auth/authSlice";
import { useDispatch } from "react-redux";
import { cookies } from "./_app";

function Register() {
  const errRef = useRef();
  const dispatch = useDispatch();

  const [idNumber, setIdNumber] = useState("");
  const [name, setName] = useState("");
  const [surname, setSurname] = useState("");
  const [gender, setGender] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [branchCodes, setBranchCodes] = useState([]);
  const [registeredBranchCode, setRegisteredBranchCode] = useState(undefined);
  const [errMsg, setErrMsg] = useState("");

  useLayoutEffect(() => {
    async function fetchAllBranchCodes() {
      try {
        const res = await getAllBranchCodes().unwrap();
        console.log("all branches:", res);
        debugger;
        setBranchCodes(res);
      } catch (err) {}
    }
    fetchAllBranchCodes();
  }, [dispatch]);

  const router = useRouter();
  const [register, { isLoading }] = useRegisterMutation();
  const [getAllBranchCodes, { isLoadingBranchCodes }] =
    useGetAllBranchCodesMutation();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (
      !/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
        email
      )
    )
      return;
    try {
      cookies.remove("Authorization");
      const jwtToken = await register({
        idNumber,
        name,
        surname,
        gender,
        email,
        password,
        phoneNumber,
        registeredBranchCode,
      }).unwrap();
      dispatch(setCredentials({ ...jwtToken }));
      if (typeof window !== "undefined") {
        localStorage.setItem("username", idNumber);
      }
      router.push("/transactions");
    } catch (err) {
      if (!err?.originalStatus) {
        setErrMsg("No Server Response");
      } else if (err.originalStatus === 400 || err.data) {
        setErrMsg(err.data);
      } else {
        setErrMsg("Login Failed");
      }
      errRef?.current?.focus();
    }
  };

  return (
    <>
      <Head>
        <title>Stuf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.page}>
          <div className={styles.pageHeader}></div>
          <div className={styles.container}>
            {errMsg && (
              <p ref={errRef} className={styles.errMsg} aria-live="assertive">
                {errMsg}
              </p>
            )}
            <form className={styles.form} action="" onSubmit={handleSubmit}>
              <input
                className={styles.input}
                type="text"
                value={idNumber}
                placeholder="ID number"
                onChange={(e) => setIdNumber(e.target.value)}
              />
              <input
                className={styles.input}
                type="text"
                value={name}
                placeholder="name"
                onChange={(e) => setName(e.target.value)}
              />
              <input
                className={styles.input}
                type="text"
                value={surname}
                placeholder="surname"
                onChange={(e) => setSurname(e.target.value)}
              />
              <input
                className={styles.input}
                type="text"
                value={gender}
                placeholder="gender"
                onChange={(e) => setGender(e.target.value)}
              />
              <input
                className={styles.input}
                type="text"
                value={email}
                placeholder="email"
                onChange={(e) => setEmail(e.target.value)}
              />
              <input
                className={styles.input}
                type="password"
                value={password}
                placeholder="password"
                onChange={(e) => setPassword(e.target.value)}
              />
              <input
                className={styles.input}
                type="text"
                value={phoneNumber}
                placeholder="phone number"
                onChange={(e) => setPhoneNumber(e.target.value)}
              />
              <select
                className={styles.input}
                id="branch-code"
                name="branch-code"
                placeholder="Registered Branch Code"
                value={registeredBranchCode}
                onChange={(e) => setRegisteredBranchCode(e.target.value)}
              >
                <option value="" selected disabled>
                  Branch Code
                </option>
                {branchCodes.map((branchCode, ind) => (
                  <option key={`ee${ind}`} value={branchCode.code}>
                    {branchCode.code}
                  </option>
                ))}
              </select>
              <button className={styles.formButton}>Sign Up</button>
            </form>

            <ul>
              <li>By signing up, you agree to our&nbsp;</li>
              <li>
                <a href="">Terms</a>
              </li>
              <li>
                <a href="">&nbsp;Data Policy&nbsp;</a>
              </li>
              <li>and</li>
              <li>
                <a href="">&nbsp;Cookies Policy</a>.
              </li>
            </ul>
          </div>
        </div>
        <div className={styles.option}>
          <p>
            Have an account? <a href="/login">Log in</a>
          </p>
        </div>
        <div className={styles.otherapps}>
          <p>Get the app, maybe</p>
          <button type="button">
            <i className="fab fa-apple"></i> App Store
          </button>
          <button type="button">
            <i className="fab fa-google-play"></i> Google Play
          </button>
        </div>
      </main>
    </>
  );
}

export default Register;
